### ISSUE TITLE
Needs work to actually find all broken links

### ISSUE THREAD

**Issue by frederickjh** [MayankPandey01/BrokenLinkHijacker#2]
I have been using another broken link tester [michaeltelford/broken_link_finder](https://github.com/michaeltelford/broken_link_finder), but am currently looking for one that is portable.  

I setup a test page with 19 broken links testing website broken link finders for the following test cases and combinations thereof:

* Absolute broken link to image
* Absolute broken link to non-existing page
* Absolute broken anchor link to non-existing page
* Absolute broken anchor link to test page
* Absolute broken link to non-existing page
* Relative broken link to image
* Relative broken link to non-existing page
* Relative broken anchor link to non-existing page
* Relative broken anchor link to test page
* Relative broken link to non-existing page
* Broken link to image on a different domain that does not exist.
* Broken link on different domain.
* Broken anchor link to non-existing page on different domain.
* Broken anchor link to existing page on  different domain.
* Broken link on different domain with query string.
* Broken Link to non-existing domain.
* Broken Link to image on non-existing domain
* Broken Anchor Link on non-existing domain
* Broken Link to non-existing domain with query string

I ran BrokenLinkHijacker against my test page.
* It found only 10 links
* It search 4 broken links saying that it could not connect, then reported
* NO BROKEN LINKS FOUND (all caps from the output of the program not mine.)

Not sure where to start. A page with 19 broken links and it does not even find one.

**Comment by MayankPandey01** [comment]
There are few reasons for the problem you are facing
If you could provide the link of the Webpage you are testing then it will be more helpful
> It found only 10 links
-  It currently only searches for link in "a href" and "img" tags (more tags will be added)

> It search 4 broken links saying that it could not connect, then reported
-  These were the links which returned status code other than 404. This is useful to determine few dead social media links which either redirect or shows other error when a Non-Existing username is given.

> NO BROKEN LINKS FOUND
-  In the broken link section only those links are shown which gives a 404 error. Other dead links are shown in "UNABLE TO CONNECT "

As this is the first release it has a few Bug. 
PR is always welcomed and appreciated.

**Comment by frederickjh** [comment]
The test page is now on GitHub here https://frederickjh.github.io/broken-link-test-website/ (The final slash is required to actually hit the page and not get GitHub's 404)

The 4 broken links it searched were not 404 but not found. These are links on a non-existent domain name.

Sorry, I think your logic is flawed about what constitutes a broken link. You seem to think that only a 404 is a broken link. There are a number of other [HTTP error codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) that should also be considered a broken link. Especially in the 400 and 500 range. In the 300 range if a link redirects too many times this should also be considered broken as a web browser will reject it. Safari seems to have the lowest at 16 redirects.

A broken link is a link that is unable to provide the resource it should link to.

**Comment by MayankPandey01** [comment]
First of all, I would suggest you read the "readme.md", this will give you an idea of how this tool works. As this tool was built for Bug Bounty hunters it was made to work fast and with reliability. This is not an SEO tool that scans for links on your domain. Its main purpose is to find Dead OUTBOUND links.
Now coming to your testing website. I will try to explain how this tool worked for your website. 

There is a total of 20 links on your website. Below is the output I got

[!] UNABLE TO CONNECT: https://thisdomaindoesnotexist-thouthou.com/nonexistenimage.png
[!] UNABLE TO CONNECT: https://thisdomaindoesnotexist-thouthou.com/badpage.html
[!] UNABLE TO CONNECT: https://example.com/images/non-existing_logo.png
[!] UNABLE TO CONNECT: https://example.com/brokenlink
[*] NO BROKEN LINKS FOUND

[+] Total Inbound links: 6
[+] Total Outbound links: 5
[+] Total URLs: 11

> Why only 11 links got detected?
-  Because only 11 links were proper links i.e  5 are relative links (This tool does not scan for relative URLs). The other 4 links were having queries in them and hence they were treated as the same despite having different queries. This happens because URLParser Parses the URL based on their directory not on their queries.

> 11 links were found and they all were dead so why only 4 links are displayed in the output?
-  This is because only the outbound links are checked whether they are dead or not. This is done because if we start to scan all the links (INBOUND + OUTBOUND) on a real target this will take an enormous amount of time. Usually, we have no control over the links that are hosted on the same domain so this can not be a big deal of security issue. So we only focus on the OUTBOUND links.  

> So why 4 in output when there are 5 outbound links.
-  Because you have put "example.com" in one of the links. It is an outbound link but not a dead one (This is an actual website)

No, I don't think that this program has flawed logic.  Only 404 is not considered a broken link. There are 3 sections in which the Output is shown

-  HTTP ERROR: For Every other HTTP CODE than 404
-  UNABLE TO CONNECT: For error like DNS not found etc
-  BROKEN LINK FOUND/NOT FOUND: Link that is giving 404 HTTP CODE error.

You can combine all these sections and have an idea of what you are dealing with.
If you think a feature can be added feel free to leave a PR.
